### ISSUE TITLE
Use a more optimized docker image

### ISSUE THREAD

**Issue by L1ghtman2k** [l1ghthouse/northstar-bot#7]
2.0.11.0-dedicated-mp-vpkoptim.951630d, as suggested by pg: https://github.com/orgs/nsres/packages/container/package/titanfall

**Comment by pg9182** [comment]
`2.0.11.0-dedicated-mp-vpkoptim.430d3bb`

**Comment by L1ghtman2k** [comment]
bootstrap time now is exactly 2 minutes
